#!/usr/bin/env bash

token="${1:-"${SUZURI_TOKEN}"}"
folder="${2:-"${SUZURI_FOLDER}"}"

if [[ -z "${token}" ]]; then
	printf "%s\n\n%s\n%s\n%s\%s\n%s\n\n%s\n%s\n%s\n%s\n" \
		"usage: sumi token [folder]" \
		"positional arguments:" \
		"  token           sumi.news session token" \
		"  folder          sumi.news feed folder" \
		"environment variables:" \
		"  SUZURI_TOKEN    substitution for [token]" \
		"  SUZURI_FOLDER   substitution for [folder]" \
		"  SUZURI_REVERSE  reverse the output feed" \
		"  SUZURI_MINIMAL  output only linked titles" \
		"  SUZURI_RAW      output raw markdown"

	exit
fi

curl_command=(
	'curl'
	'--silent'
	'--cookie'
	"s=${token}"
)

if [[ -n "${folder}" ]]; then
	curl_command+=("https://sumi.news/?folder=${folder}")
else
	curl_command+=("https://sumi.news/")
fi

body="$("${curl_command[@]}" | pup '.mt-6' | html2md -i)"

if [[ -n "${SUZURI_REVERSE}" ]]; then
	body="$(echo "${body}" | tac)"
fi

if [[ -n "${SUZURI_MINIMAL}" ]]; then
	body="$(echo "${body}" | grep "##" | sed "s/##//")"
fi

if [[ -n "${SUZURI_RAW}" ]]; then
	echo "${body}"
else
	if [[ -n "${SUZURI_MINIMAL}" ]]; then
		echo "${body}" | glow -w 1
	else
		echo "${body}" | glow
	fi
fi
