#!/usr/bin/env bash

ROOT_URL="https://sumi.news/"
token="${1:-"${SUZURI_TOKEN}"}"
folder="${2:-"${SUZURI_FOLDER}"}"

if [[ -z "${token}" ]]; then
	cat <<EOF
usage: $(basename "${0}") token [folder]

positional arguments:
  token           sumi.news session token
  folder          sumi.news feed folder

environment variables:
  SUZURI_TOKEN    substitution for token
  SUZURI_FOLDER   substitution for folder
  SUZURI_REVERSE  reverse the output feed
  SUZURI_MINIMAL  output only linked titles
  SUZURI_RAW      output raw markdown
EOF

	exit
fi

curl_command=(
	'curl'
	'--silent'
	'--cookie'
	"s=${token}"
)

if [[ -n "${folder}" ]]; then
	curl_command+=("${ROOT_URL}?folder=${folder}")
else
	curl_command+=("${ROOT_URL}")
fi

body="$("${curl_command[@]}" | pup '.mt-6' | html2md -i || true)"

if [[ -n "${SUZURI_REVERSE}" ]]; then
	body="$(echo "${body}" | tac)"
fi

if [[ -n "${SUZURI_MINIMAL}" ]]; then
	body="$(echo "${body}" | grep "##" | sed "s/##//" || true)"
fi

if [[ -n "${SUZURI_RAW}" ]]; then
	echo "${body}"
else
	if [[ -n "${SUZURI_MINIMAL}" ]]; then
		echo "${body}" | glow -w 1
	else
		echo "${body}" | glow
	fi
fi
